#!/usr/bin/env bash
# Configures your Nginx server so that /redirect_me is redirecting to another page

# Updates Packages and install nginx server
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Modifies 301 redirection
redirection_url="https:\/\/youtu.be\/nuNvRFOXn3w?si=JvnxyjMZY0E4ifC4"
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me $redirection_url permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart
