#!/usr/bin/env bash
# Configures your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
sudo chmod -R 777 /etc/nginx
echo "Hello World!" > /var/www/html/index.html

# Overwrites the contents of /redirect_me. Redirects to a youtube video
sed -i '37i\rewrite ^/redirect_me https://youtu.be/nuNvRFOXn3w?si=JvnxyjMZY0E4ifC4 permanent;' /etc/nginx/sites-available/default

# Creates a custom 404 page
echo "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
