#!/usr/bin/env bash
# Configures a new Nginx server to have a custom 404 page, redirect link, and a custom HTTP response header

# updates packages and install nginx
sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Overwrites the contents of /redirect_me. Redirects to a youtube video
echo "https://youtu.be/nuNvRFOXn3w?si=JvnxyjMZY0E4ifC4" | sudo tee /var/www/html/redirect_me
REPLACEMENT="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtu.be\/nuNvRFOXn3w?si=JvnxyjMZY0E4ifC4 permanent;"
sudo sed -i "s/server_name;/$REPLACEMENT/" /etc/nginx/sites-available/default

# Creates a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html; \n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$replacement_string/" /etc/nginx/sites-available/default

# creates a custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# restart the server to implement changes
sudo service nginx restart
