#!/usr/bin/env bash
#prints To infinity and beyond indefinitely.
#when receiving a SIGTERM signal, prints I am invincible!!!

while true
do
echo "To infinity and beyond"
sleep 2
trap 'echo "I am invincible!!!"' SIGTERM
done
