#!/usr/bin/env bash
#prints "Best school" then at 4 "bad luck" at 8 "good luck"

i=1
while(("$i" < 11)); do
    if [ $i -eq 4 ]; then
    echo "bad luck"
    elif [ $i -eq 8 ]; then
    echo "good luck"
    else
    echo "Best School"
    fi
    ((i++))
done
