#!/usr/bin/env bash
#displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

List=$(ls)
for i in $List; do
	echo "$i" | cut -d "-" -f2
done
