#!/usr/bin/env bash
# Installs and configures ufw firewall to block all incoming traffic except TCP
# ports 22 (SSH), 443 (HTTPS SSL), and 80 (HTTP)

# Updates the system and installs ufw firewall
sudo apt-get update -y
sudo apt-get install ufw -y

# Configures the ufw to allow the stated ports
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 22/tcp

# Sets the default action for incoming traffic to "deny"
sudo ufw default deny incoming

# Enable ufw after configurations
sudo ufw -y enable
