#!/usr/bin/env bash

# Configures Nginx to run as user Nginx and listen to all active IPs on port 8080
sed -i "s/#user www-data;/user nginx nginx;/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2

# start the nginx service as the nginx user
sudo -u nginx service nginx start
